tree1 =98
tree2 =94
tree3 =41
tree4 =96
tree5 =11
sum = tree1 + tree2 + tree3 + tree4 + tree5
print ("the sum of all the trees in jacks backyard =" , sum)
average = sum/5
print ("the average of all the trees in jacks backyard =" , average)
